#!/bin/sh
read -p "파일/디렉토리 이름 입력 [enter] " filename

if [ ! -e "$filename" ]; then
    echo "$filename 은 존재하지 않습니다."
elif [ -L "$filename" ]; then
    echo "$filename 은 심볼릭링크 입니다."
elif [ -d "$filename" ]; then
    echo "$filename 은 디렉토리 입니다."
elif [ -b "$filename" ]; then
    echo "$filename 은 블록장치 입니다."
elif [ -c "$filename" ]; then
    echo "$filename 은 문자장치 입니다."
elif [ -f "$filename" ]; then
    echo "$filename 은 보통파일 입니다."
# 파이프(-p)와 소켓(-S)은 표준 test 옵션이나 강의안 기본 속성을 따름
elif [ -p "$filename" ]; then
    echo "$filename 은 파이프 입니다."
elif [ -S "$filename" ]; then
    echo "$filename 은 소켓 입니다."
fi
